/**
 * generate_full_catalog.cjs
 * Generates 200+ products with HD Unsplash images for nepal-store
 * Outputs: public/products.json, public/traditional.json, public/marketplace.json
 * Run: node generate_full_catalog.cjs
 */

const fs = require("fs");
const path = require("path");

// ─── Utility helpers ────────────────────────────────────────────────
function rand(min, max) { return Math.floor(Math.random() * (max - min + 1)) + min; }
function pick(arr) { return arr[rand(0, arr.length - 1)]; }
function shuffle(arr) { return [...arr].sort(() => Math.random() - 0.5); }
function rating() { return (4 + Math.random() * 0.9).toFixed(1); }
function reviews() { return rand(50, 500); }
function stock() { return rand(10, 200); }
function sold() { return rand(0, 500); }
function isNew(idx, total, pct = 0.2) { return idx < Math.floor(total * pct); }
function freeShipping(price) { return price >= 5000; }
function img(photoId, w = 1200) {
  return `https://images.unsplash.com/photo-${photoId}?q=80&w=${w}&auto=format&fit=crop`;
}

// ─── Unsplash Photo ID pools by theme ───────────────────────────────
const photos = {
  cashmere:   ["1434387367598","1434387477355","1434387477352","1576565238778","1520903442860","1606760227091","1564485377539"],
  fabric:     ["1558171348","1528459801416","15581713483f0a193","1617627143750","1594938298603","1598300042247"],
  jewelry:    ["1535632066927","1515562141207","1573408391685","1590874103328","1591561954557","1602173572773"],
  pottery:    ["1565193980688","1578574423627","156577988","1572607789097"],
  nature:     ["1506905929246","1464822759023","1464822759","1501709118575","1486308533570"],
  fashion:    ["1509631179647","1515886657613","1490481651871","1515462277125","1620799140408","1610030469983"],
  home:       ["1556228453","1586023492125","1556906781","1563822796473","1513694203232","1583847268964"],
  food:       ["1563822796473","155667988","1495522640386","1509631179647"],
  yoga:       ["1544367563195","1599440131243","1506126613426","1518611096518"],
  trekking:   ["1551607916430","1523275335684","1460353581641","1483985988355"],
  sports:     ["1542291026","1595950653106","1606107557195","1511746310427","15569067819a41296"],
  kids:       ["1503454590009","1516331138075","1515462277125","1522713278287"],
  baby:       ["1519689147854","1555252338356","1596039233736","1515462277125"],
  beauty:     ["1596462906757","1571786183568","1556228578","1598448794320"],
  electronics:["1523275335684","1505784704326","1546878649355","1583391733956"],
  traditional:["1582991040332","1605648911177","1514222139775","1540206351","1519414442741"],
  leather:    ["1548047995397","1559559885","1543332163484"],
  wooden:     ["1558618666155","1558618666","1586023492125"],
  silk:       ["1617627143750","1610030469983","1595777457583"],
  cotton:     ["1591195853828","1596755094514","1562577309"],
  wool:       ["1576871337632","1543076447","1571019614242"],
  mountain:   ["1506905929246","1464822759023","1486308533570","1501709118575"],
};

// ─── Color palettes ─────────────────────────────────────────────────
const COLORS = {
  red:       [{ name: "Crimson", hex: "#DC143C" }, { name: "Maroon", hex: "#800000" }, { name: "Ruby", hex: "#9B111E" }],
  blue:      [{ name: "Navy", hex: "#1B2A4A" }, { name: "Sky", hex: "#87CEEB" }, { name: "Indigo", hex: "#4B0082" }],
  green:     [{ name: "Emerald", hex: "#50C878" }, { name: "Forest", hex: "#228B22" }, { name: "Sage", hex: "#BCB88A" }],
  gold:      [{ name: "Gold", hex: "#FFD700" }, { name: "Champagne", hex: "#F7E7CE" }, { name: "Amber", hex: "#DD6B20" }],
  earth:     [{ name: "Earth", hex: "#4A3728" }, { name: "Sand", hex: "#C2B280" }, { name: "Khaki", hex: "#C3B091" }],
  neutral:   [{ name: "Obsidian", hex: "#0A0A0A" }, { name: "Summit White", hex: "#FFFFFF" }, { name: "Charcoal", hex: "#36454F" }],
  pastel:    [{ name: "Blush", hex: "#FBB6CE" }, { name: "Lavender", hex: "#E6E6FA" }, { name: "Mint", hex: "#98FF98" }],
  festival:  [{ name: "Saffron", hex: "#D4A017" }, { name: "Vermillion", hex: "#E34234" }, { name: "Turmeric", hex: "#E8B830" }],
  winter:    [{ name: "Plum", hex: "#553C7B" }, { name: "Snow", hex: "#F7FAFC" }, { name: "Charcoal", hex: "#2D3748" }],
  monsoon:   [{ name: "Storm Gray", hex: "#4A5568" }, { name: "Rain Blue", hex: "#2B6CB0" }, { name: "Moss", hex: "#386641" }],
  himalayan: [{ name: "Himalayan Blue", hex: "#4682B4" }, { name: "Snow White", hex: "#FFFAFA" }, { name: "Rock Gray", hex: "#708090" }],
};

// ─── Product catalog definitions ────────────────────────────────────
const catalogDefs = {
  WOMEN: [
    { slug: "cashmere-pashmina-shawl", names: ["Pashmina Shawl — Kathmandu Weave","Pashmina Shawl — Pokhara Mist","Pashmina Shawl — Mustang Dawn","Cashmere Wrap — Annapurna Gold","Pashmina Stole — Rara Lake"], img: photos.cashmere, desc: (n) => `Luxurious 100% Himalayan cashmere ${n}, hand-loomed by artisan women's cooperatives in the Kathmandu Valley. Ultra-soft fibers from Chyangra goats grazing at 4,000m in the Upper Mustang region. Naturally dyed with traditional paisley and lotus motifs. Perfect for chilly mountain evenings or elegant city wear.`, prices: [8500,25000], sizes: ["One Size"], colors: ["earth","gold","neutral","red"] },
    { slug: "dhaka-kurta", names: ["Dhaka Kurta — Bhaktapur Classic","Dhaka Kurta — Patan Heritage","Dhaka Kurta — Thamel Modern","Dhaka Tunic — Newari Rose","Dhaka Top — Festival Bloom"], img: photos.fabric, desc: (n) => `Elegant Dhaka fabric kurta with geometric weave patterns native to eastern Nepal. Hand-woven on traditional pit looms, each piece takes 3-5 days to complete. Features mandarin collar and mother-of-pearl buttons. A celebration of Nepali textile heritage.`, prices: [2500,6500], sizes: ["XS","S","M","L","XL"], colors: ["festival","red","gold"] },
    { slug: "silk-sari", names: ["Silk Sari — Banarasi Gold","Silk Sari — Terai Sunset","Silk Sari — Janakpur Jewel","Silk Sari — Mithila Art","Silk Sari — Royal Crimson"], img: photos.silk, desc: (n) => `Exquisite handwoven silk sari with real zari work. Inspired by the Mithila art tradition of the Terai plains, featuring intricate border patterns and a rich contrasting pallu. Woven on traditional handlooms — a masterpiece for weddings and festivals.`, prices: [12000,35000], sizes: ["One Size"], colors: ["red","gold","festival"] },
    { slug: "woolen-cardigan", names: ["Woolen Cardigan — Langtang Knit","Wool Cardigan — Dolpo Storm","Woolen Wrap — Mustang Wind","Cardigan — Helambu Heritage","Woolen Coat — Everest Base"], img: photos.wool, desc: (n) => `Chunky-knit woolen cardigan crafted from Nepalese mountain sheep wool. Wooden toggle buttons, deep patch pockets, and ribbed cuffs. Perfect layering piece for Kathmandu's winter mornings or trekking base camps.`, prices: [3500,9500], sizes: ["S","M","L","XL"], colors: ["earth","winter","neutral"] },
    { slug: "gunyo-cholo", names: ["Gunyo Cholo — Crimson Silk","Gunyo Cholo — Royal Blue","Gunyo Cholo — Emerald Garden","Gunyo Cholo — Gold Thread","Gunyo Cholo — Festival Red"], img: photos.fashion, desc: (n) => `Authentic hand-stitched Gunyo Cholo, the traditional Nepali women's ensemble. Vibrant silk fabric with intricate border embroidery and traditional hook-and-eye closure. A timeless symbol of Nepali femininity, worn during Dashain, Tihar, and wedding ceremonies.`, prices: [5500,15000], sizes: ["XS","S","M","L","XL"], colors: ["red","gold","festival"] },
    { slug: "modern-dress", names: ["Modern Dress — Thamel Night","Modern Dress — Lakeside Pokhara","Modern Dress — Kathmandu Chic","Dress — Nagarkot Sunrise","Dress — Boudha Evening"], img: photos.fashion, desc: (n) => `Contemporary dress blending Nepali textile traditions with modern silhouettes. Features hand-block printed patterns inspired by mandala art and Himalayan flora. Breathable cotton-silk blend, A-line cut — versatile from office to evening.`, prices: [3000,8500], sizes: ["XS","S","M","L","XL"], colors: ["neutral","pastel","earth"] },
    { slug: "shawl-wrap", names: ["Shawl Wrap — Himalayan Drape","Shawl Wrap — Ylang Ylang","Shawl Wrap — Rhododendron","Wrap Stole — Garden of Dreams","Shawl Wrap — Midnight Kathmandu"], img: photos.cashmere, desc: (n) => `Versatile shawl wrap in a soft blend of cashmere and merino wool. Generous sizing for multiple draping styles — from classic shoulder wrap to full body shawl. Hand-rolled edges with subtle fringe detail.`, prices: [4000,12000], sizes: ["One Size"], colors: ["neutral","winter","earth"] },
    { slug: "cashmere-sweater", names: ["Cashmere Sweater — Yeti Knit","Cashmere Crew — Snow Leopard","Cashmere V-Neck — Annapurna","Cashmere Pullover — Manaslu","Cashmere Turtleneck — Kanchenjunga"], img: photos.cashmere, desc: (n) => `Premium cashmere sweater from the high-altitude herds of Dolpo. Fine-gauge knit with ribbed hem and cuffs. Incredibly lightweight yet warm — the ultimate mountain luxury. Each sweater supports fair-trade artisan partnerships.`, prices: [6000,18000], sizes: ["S","M","L","XL"], colors: ["neutral","winter","earth"] },
    { slug: "hemp-jacket", names: ["Hemp Jacket — Everest Eco","Hemp Blazer — Green Kathmandu","Hemp Jacket — Organic Valley","Allo Jacket — Mountain Fiber","Hemp Coat — Sustainable Nepal"], img: photos.fabric, desc: (n) => `Eco-friendly hemp jacket crafted from Nepalese allo (Himalayan nettle fiber). Naturally antimicrobial, UV-resistant, and gets softer with each wash. Structured blazer cut with traditional dhaka fabric lining.`, prices: [4500,11000], sizes: ["S","M","L","XL"], colors: ["earth","green","neutral"] },
    { slug: "linen-pants", names: ["Linen Pants — Terai Breeze","Linen Trousers — Chitwan Walk","Linen Wide-Leg — Bardia Sun","Linen Palazzo — Ilam Tea Garden","Linen Pants — Monsoon Light"], img: photos.cotton, desc: (n) => `Breathable linen trousers perfect for Nepal's warm Terai climate. Wide-leg silhouette with elasticated waist and deep side pockets. Pre-washed for a soft, lived-in feel from day one.`, prices: [2000,5500], sizes: ["XS","S","M","L","XL"], colors: ["neutral","earth","pastel"] },
  ],
  MEN: [
    { slug: "daura-suruwal", names: ["Daura Suruwal — Kathmandu Formal","Daura Suruwal — Patan Classic","Daura Suruwal — Bhaktapur Gold","Daura Set — Gorkha Heritage","Daura Suruwal — Royal Nepal"], img: photos.fashion, desc: (n) => `Traditional Nepali Daura Suruwal set with eight sacred tie-strings (pattuka) on the daura. Fine cotton or wool blend with structured suruwal trousers. The national dress of Nepal — worn for official ceremonies, Dashain tika, and formal occasions.`, prices: [6000,18000], sizes: ["S","M","L","XL","XXL"], colors: ["neutral","earth","gold"] },
    { slug: "dhaka-topi", names: ["Dhaka Topi — National Pride","Dhaka Topi — Geometric Red","Dhaka Topi — Rainbow Weave","Dhaka Cap — Heritage Gold","Topi — Kathmandu Classic"], img: photos.fabric, desc: (n) => `Nepal's iconic national headwear, hand-loomed in vibrant Dhaka fabric with traditional geometric patterns. Stiffened crown with comfortable sweatband lining. The symbol of Nepali identity and pride.`, prices: [800,3500], sizes: ["S","M","L","XL"], colors: ["festival","red","gold"] },
    { slug: "cashmere-blazer", names: ["Cashmere Blazer — Mustang Executive","Cashmere Jacket — Himalayan CEO","Blazer — Kathmandu Boardroom","Cashmere Coat — Dolpo Elite","Blazer — Everest Premium"], img: photos.cashmere, desc: (n) => `Tailored cashmere blazer blending Himalayan luxury with modern business style. Single-breasted, notch lapel, fully lined with silk. Crafted from the finest Chyangra cashmere — Nepal's softest fiber.`, prices: [15000,45000], sizes: ["S","M","L","XL","XXL"], colors: ["neutral","earth","winter"] },
    { slug: "woolen-coat", names: ["Woolen Coat — Himalayan Winter","Wool Overcoat — Annapurna Frost","Wool Coat — Langtang Storm","Overcoat — Mustang Freeze","Woolen Coat — K2 Classic"], img: photos.wool, desc: (n) => `Heavy woolen overcoat built for Nepal's harsh mountain winters. Double-breasted with wide lapels, deep pockets, and warm flannel lining. Premium Nepalese sheep wool — naturally water-resistant and windproof.`, prices: [8000,25000], sizes: ["S","M","L","XL","XXL"], colors: ["neutral","winter","earth"] },
    { slug: "hemp-shirt", names: ["Hemp Shirt — Eco Kathmandu","Hemp Button-Down — Organic Nepal","Hemp Shirt — Allo Classic","Casual Hemp — Mountain Fresh","Hemp Shirt — Terai Green"], img: photos.fabric, desc: (n) => `Casual hemp button-down shirt crafted from Nepalese allo fiber. Breathable, moisture-wicking, and naturally antibacterial. Relaxed fit with coconut shell buttons and a single chest pocket.`, prices: [2000,5500], sizes: ["S","M","L","XL","XXL"], colors: ["earth","green","neutral"] },
    { slug: "traditional-vest", names: ["Weston Waistcoat — Brocade Gold","Traditional Vest — Dhaka Weave","Waistcoat — Newari Heritage","Vest — Bhadrain Classic","Waistcoat — Festival Brocade"], img: photos.fashion, desc: (n) => `Traditional Nepali Weston waistcoat in rich brocade fabric. Five-button closure with silk lining and embroidered pockets. Worn over daura or kurta for formal occasions and wedding celebrations.`, prices: [3000,8500], sizes: ["S","M","L","XL"], colors: ["gold","red","festival"] },
    { slug: "modern-suit", names: ["Modern Suit — Kathmandu Slim","Suit — Thamel Tailored","Suit — Lakeside Modern","Slim Suit — Everest Cut","Suit — Nepal Executive"], img: photos.fashion, desc: (n) => `Contemporary slim-fit suit tailored for the modern Nepali professional. Dhaka fabric accent on inner collar and pocket square. Premium wool blend with stretch comfort for all-day wear.`, prices: [12000,35000], sizes: ["S","M","L","XL","XXL"], colors: ["neutral","winter","earth"] },
    { slug: "pashmina-scarf", names: ["Pashmina Scarf — Himalayan Drape","Pashmina Muffler — Mustang","Scarf — Kathmandu Winter","Pashmina Wrap — Dolpo Soft","Scarf — Pokhara Breeze"], img: photos.cashmere, desc: (n) => `Pure pashmina scarf for men, woven in the high Himalayas. Lightweight yet incredibly warm. Classic solid colors with hand-fringed edges. The perfect gift for someone who appreciates understated luxury.`, prices: [3500,12000], sizes: ["One Size"], colors: ["neutral","earth","winter"] },
    { slug: "denim-jacket", names: ["Denim Jacket — Himalayan Rugged","Denim — Kathmandu Street","Denim Jacket — Nepal Urban","Jacket — Everest Denim","Denim — Thamel Rock"], img: photos.fashion, desc: (n) => `Rugged denim jacket with subtle Nepali design touches — dhaka fabric inner collar, hand-embroidered back patch. Premium selvedge denim that ages beautifully. Street-ready style from the hills of Kathmandu.`, prices: [4000,9500], sizes: ["S","M","L","XL","XXL"], colors: ["neutral","earth"] },
    { slug: "formal-wear", names: ["Sherwani — Royal Wedding","Formal Coat — Diplomat Nepal","Sherwani — Kathmandu Royal","Formal Set — Ambassador","Sherwani — Heritage Gold"], img: photos.fashion, desc: (n) => `Luxurious sherwani and formal coat set for Nepal's grandest occasions. Heavy silk brocade with gold embroidery, paired with fitted churidar trousers. Inspired by the Rana-era court dress of Nepal.`, prices: [18000,55000], sizes: ["S","M","L","XL"], colors: ["gold","red","festival"] },
  ],
  TRADITIONAL: [
    { slug: "handwoven-dhaka", names: ["Dhaka Fabric — Bhaktapur Loom","Dhaka Weave — Eastern Nepal","Dhaka Fabric — Patan Heritage","Dhaka Cloth — Traditional Geometric","Dhaka — Rainbow Meter"], img: photos.fabric, desc: (n) => `Premium hand-woven Dhaka fabric sold by the meter. Vibrant geometric patterns created on traditional pit looms in eastern Nepal. Used for topis, coats, bags, and home decor. Each meter represents hours of skilled artisan labor.`, prices: [600,2500], sizes: ["1m","2m","3m","5m"], colors: ["festival","red","gold"] },
    { slug: "singing-bowl", names: ["Singing Bowl — Tibetan Healing","Singing Bowl — Kathmandu Temple","Singing Bowl — Seven Metal","Bowl — Boudhanath Resonance","Singing Bowl — Meditation Gold"], img: photos.traditional, desc: (n) => `Hand-hammered Tibetan singing bowl crafted from seven sacred metals (gold, silver, copper, iron, tin, mercury, zinc). Each bowl is tuned to a specific chakra frequency. Comes with wooden striker and silk cushion. Made in the workshops near Boudhanath Stupa.`, prices: [2500,15000], sizes: ["Small (4\")","Medium (6\")","Large (8\")","XL (10\")"], colors: ["gold","earth","neutral"] },
    { slug: "thangka-painting", names: ["Thangka — White Tara","Thangka — Buddha's Enlightenment","Thangka — Mandala of Compassion","Thangka — Green Tara Gold","Thangka — Wheel of Life"], img: photos.traditional, desc: (n) => `Hand-painted Thangka scroll art following centuries-old Tibetan Buddhist iconography. Natural mineral pigments on cotton canvas with 24k gold detailing. Each painting takes 3-6 months to complete by master artists in the Kathmandu Valley. Certified authentic with artisan signature.`, prices: [8000,75000], sizes: ["12x18\"","18x24\"","24x36\"","36x48\""], colors: ["gold","festival","earth"] },
    { slug: "prayer-wheel", names: ["Prayer Wheel — Copper Mantra","Prayer Wheel — Hand-Carved Wood","Prayer Wheel — Silver Inlay","Prayer Wheel — Temple Size","Prayer Wheel — Portable Brass"], img: photos.traditional, desc: (n) => `Traditional Tibetan prayer wheel filled with thousands of handwritten "Om Mani Padme Hum" mantras. Hand-crafted from copper, brass, or silver-plated metal. Spinning the wheel is believed to accumulate wisdom and merit. Wall-mounted or handheld designs available.`, prices: [1500,12000], sizes: ["Small","Medium","Large","Temple"], colors: ["gold","earth","neutral"] },
    { slug: "mala-beads", names: ["Mala — Rudraksha 108","Mala — Bodhi Seed","Mala — Crystal Quartz","Mala — Sandalwood","Mala — Lotus Seed"], img: photos.jewelry, desc: (n) => `Hand-strung prayer mala with 108 beads plus guru bead. Made from sacred rudraksha seeds, bodhi seeds, or natural gemstones. Used for meditation, mantra recitation, and mindfulness practice. Comes in a handwoven dhaka pouch.`, prices: [800,5500], sizes: ["One Size"], colors: ["earth","gold","neutral"] },
    { slug: "khukuri", names: ["Khukuri — Gorkha Warrior","Khukuri — Panawal Blade","Khukuri — Bhojpur Forge","Khukuri — Traditional 12\"","Khukuri — Collector's Edition"], img: photos.traditional, desc: (n) => `Authentic Gorkha khukuri hand-forged by traditional blacksmiths in Bhojpur district. High-carbon steel blade with water-buffalo horn handle and leather sheath. The iconic curved blade of the Gorkha regiment — a symbol of Nepali bravery. Includes certificate of authenticity.`, prices: [3500,25000], sizes: ["9\"","12\"","14\"","16\"","18\""], colors: ["earth","neutral"] },
    { slug: "pottery", names: ["Pottery — Bhaktapur Terracotta","Pottery — Traditional Water Vessel","Pottery — Hand-thrown Bowl","Pottery — Madhav Narayan Clay","Pottery — Festival Diya Set"], img: photos.pottery, desc: (n) => `Hand-thrown terracotta pottery from the ancient pottery squares of Bhaktapur. Using techniques passed down through Newari artisan families for generations. Each piece is sun-dried, kiln-fired, and naturally finished. Perfect for home decor or practical use.`, prices: [500,4500], sizes: ["Small","Medium","Large","Set of 3"], colors: ["earth","red","neutral"] },
    { slug: "carved-mask", names: ["Carved Mask — Lakhe Dance","Carved Mask — Mahakali Fierce","Carved Mask — Masked Dance Drama","Mask — Newari Temple Guardian","Mask — Festival Performance"], img: photos.traditional, desc: (n) => `Hand-carved wooden mask depicting characters from Nepal's traditional masked dance dramas. Carved from light neem wood with vibrant mineral paint. Used in festivals and ceremonies, now collected as art pieces worldwide.`, prices: [2000,12000], sizes: ["Small (8\")","Medium (12\")","Large (16\")"], colors: ["red","festival","gold"] },
    { slug: "mandala-art", names: ["Mandala — Sand Painting","Mandala — Vajra Gold","Mandala — Lotus Design","Mandala — Kalachakra","Mandala — Tibetan Cosmic"], img: photos.traditional, desc: (n) => `Intricate mandala art printed or hand-painted on premium canvas or rice paper. Sacred geometric patterns representing the universe in Buddhist and Hindu traditions. Available as wall art, tapestries, or framed prints.`, prices: [800,8500], sizes: ["12x12\"","18x18\"","24x24\"","36x36\""], colors: ["gold","festival","neutral"] },
    { slug: "handcrafted-jewelry", names: ["Jewelry — Newari Temple Set","Jewelry — Turquoise Drop","Jewelry — Coral Silver","Jewelry — Himalayan Gem","Jewelry — Pote Beaded"], img: photos.jewelry, desc: (n) => `Handcrafted jewelry inspired by Newari temple art and Himalayan gemstone traditions. Sterling silver with natural turquoise, coral, or amber stones. Each piece is made by artisan silversmiths in the Patan Durbar area.`, prices: [1500,25000], sizes: ["One Size"], colors: ["gold","earth","festival"] },
  ],
  SEASONAL: [
    { slug: "winter-cashmere-wrap", names: ["Winter Cashmere Wrap — Himalayan Night","Cashmere Wrap — Everest Snow","Wrap — Kathmandu Frost","Winter Wrap — Mustang Cold","Wrap — Annapurna Ice"], img: photos.cashmere, desc: (n) => `Oversized winter cashmere wrap for Nepal's coldest months. 100% Himalayan cashmere in generous shawl dimensions. Hand-loomed in Kathmandu with traditional border patterns. Wraps around shoulders and head for ultimate warmth.`, prices: [8000,22000], sizes: ["One Size"], colors: ["winter","neutral","earth"], tags: ["winter","cashmere","festival-season"] },
    { slug: "monsoon-rain-gear", names: ["Monsoon Poncho — Trek Rain","Rain Jacket — Kathmandu Shower","Poncho — Monsoon Trekker","Rain Cover — Himalayan Storm","Rain Gear — Nepal Wet Season"], img: photos.trekking, desc: (n) => `Lightweight waterproof rain gear designed specifically for Nepal's intense monsoon season (June-September). Breathable mesh lining, sealed seams, and packable design. Essential for trekking and daily commuting in Kathmandu.`, prices: [1500,6500], sizes: ["S","M","L","XL"], colors: ["monsoon","neutral"], tags: ["monsoon","rain","trekking","waterproof"] },
    { slug: "summer-cotton", names: ["Summer Cotton Kurta — Terai Heat","Cotton Dress — Pokhara Lake","Cotton Shirt — Kathmandu Warm","Summer Set — Chitwan Sun","Cotton Pants — Ilam Cool"], img: photos.cotton, desc: (n) => `Breathable cotton clothing designed for Nepal's hot summer months (April-June). Hand-block printed with natural dyes, loose-fitting silhouettes for maximum airflow. Perfect for the Terai plains and Kathmandu valley heat.`, prices: [1200,4500], sizes: ["XS","S","M","L","XL"], colors: ["pastel","neutral","earth"], tags: ["summer","cotton","breathable"] },
    { slug: "dashain-tika-set", names: ["Dashain Tika Set — Family Blessing","Tika Set — Jamara Gold","Dashain Combo — Festival Complete","Tika Set — Vijaya Dashami","Dashain Gift — Blessing Box"], img: photos.traditional, desc: (n) => `Complete Dashain tika set with red vermillion (abir), rice grains (jamara seeds), gold thread, and ceremonial cloth. Beautifully packaged in a hand-carved wooden box. Nepal's biggest and most important festival — celebrating the victory of good over evil.`, prices: [1500,5500], sizes: ["One Size"], colors: ["festival","red","gold"], tags: ["dashain","festival","tika","nepali-new-year"] },
    { slug: "tihar-diya-lamp", names: ["Tihar Diya — Brass Oil Lamp","Diya Set — Festival of Lights","Tihar Lamp — Clay Traditional","Diya — Laxmi Puja Gold","Tihar Set — Five Day Lights"], img: photos.traditional, desc: (n) => `Traditional brass and clay diya (oil lamp) set for Tihar — Nepal's festival of lights. Hand-crafted by Newari artisans in Bhaktapur. Includes 5, 7, or 12 diyas with cotton wicks. Illuminates homes during the five-day celebration honoring Laxmi, the goddess of wealth.`, prices: [800,4500], sizes: ["Set of 5","Set of 7","Set of 12"], colors: ["gold","festival"], tags: ["tihar","diya","festival-of-lights","laxmi-puja"] },
    { slug: "holi-colors", names: ["Holi Colors — Natural Organic","Holi Powder — Festival Set","Holi — Herbal Safe Colors","Holi Set — Nepal Celebration","Holi — Rangoli Natural"], img: photos.traditional, desc: (n) => `Natural, skin-safe Holi colors made from flower extracts, herbs, and organic ingredients. Celebrate the festival of colors (Fagu Purnima) in Nepal without chemical harshness. Includes 6 vibrant colors in reusable pouches.`, prices: [500,2500], sizes: ["6 Pack","12 Pack","Party Size"], colors: ["festival","red","gold"], tags: ["holi","festival","natural","organic","colors"] },
    { slug: "lhosar-traditional", names: ["Lhosar Outfit — Tamang Heritage","Lhosar Dress — Gurung Gold","Lhosar Set — Sherpa New Year","Traditional — Lhosar Celebration","Lhosar Wear — Tibetan Style"], img: photos.fashion, desc: (n) => `Traditional Lhosar celebration wear for the Tibetan, Gurung, and Tamang New Year festivals. Features vibrant colors, traditional patterns, and hand-woven fabrics. Includes top, bottom, and accessories for a complete festive look.`, prices: [5000,18000], sizes: ["S","M","L","XL"], colors: ["festival","red","gold"], tags: ["lhosar","tibetan-new-year","gurung","tamang","sherpa"] },
  ],
  SPORTS: [
    { slug: "trekking-gear", names: ["Trekking Jacket — Everest Base Camp","Trek Pants — Annapurna Circuit","Trekking Vest — Langtang Trail","Gear Set — Himalayan Trek","Trek Shirt — Mardi Himal"], img: photos.trekking, desc: (n) => `Professional trekking gear designed for Nepal's Himalayan trails. Moisture-wicking fabric, UV protection, and reinforced stitching for rugged terrain. Tested on Everest Base Camp, Annapurna Circuit, and Langtang Valley routes.`, prices: [2500,15000], sizes: ["S","M","L","XL","XXL"], colors: ["himalayan","neutral","earth"], tags: ["trekking","himalaya","everest","outdoor","adventure"] },
    { slug: "yoga-wear", names: ["Yoga Set — Boudha Flow","Yoga Pants — Himalayan Zen","Yoga Top — Kathmandu Stretch","Yoga Mat Bag — Meditation","Yoga Set — Peaceful Asana"], img: photos.yoga, desc: (n) => `Comfortable yoga wear inspired by the meditative traditions of Nepal. Four-way stretch fabric, moisture-wicking, and breathable. Perfect for yoga retreats in Pokhara, meditation sessions at Boudhanath, or daily practice.`, prices: [1500,6500], sizes: ["XS","S","M","L","XL"], colors: ["neutral","pastel","earth"], tags: ["yoga","meditation","boudha","mindfulness","stretch"] },
    { slug: "running-clothes", names: ["Running Tee — Kathmandu Marathon","Running Shorts — Nepal Trail Run","Running Jacket — City Dash","Running Set — Himalayan Sprint","Running Tank — Pokhara Pace"], img: photos.sports, desc: (n) => `Lightweight running apparel for Nepal's growing running community. Quick-dry fabric, reflective strips for early morning runs, and ergonomic seams. Designed for the Kathmandu Marathon, trail runs, and daily training.`, prices: [1200,5500], sizes: ["XS","S","M","L","XL"], colors: ["neutral","himalayan","festival"], tags: ["running","marathon","trail","kathmandu","quick-dry"] },
    { slug: "cycling-jersey", names: ["Cycling Jersey — Mustang Ride","Cycling Jersey — Pokhara Loop","Jersey — Himalayan Climb","Cycling Set — Nepal Mountains","Jersey — Annapurna Circuit"], img: photos.sports, desc: (n) => `Performance cycling jersey with bold Himalayan mountain graphics. Full zip, three rear pockets, silicone grip hem, and UPF 50+ protection. Designed for the challenging climbs of the Annapurna and Mustang regions.`, prices: [2000,7500], sizes: ["S","M","L","XL","XXL"], colors: ["himalayan","neutral","festival"], tags: ["cycling","mountain-biking","mustang","performance","jersey"] },
    { slug: "hiking-boots", names: ["Hiking Boots — Gorkha Trail","Hiking Boots — Everest Pro","Boots — Annapurna Grip","Boots — Langtang Explorer","Hiking Boots — Nepal Summit"], img: photos.trekking, desc: (n) => `Rugged hiking boots built for Nepal's diverse terrain — from muddy jungle trails to rocky mountain passes. Waterproof leather upper, Vibram sole, ankle support, and breathable membrane. Tested by Sherpa guides.`, prices: [5000,22000], sizes: ["6","7","8","9","10","11","12"], colors: ["earth","neutral"], tags: ["hiking","boots","waterproof","trekking","sherpa"] },
    { slug: "gym-wear", names: ["Gym Set — Kathmandu Fit","Gym Tank — Nepal Strength","Gym Shorts — Urban Power","Gym Leggings — Himalayan Lift","Gym Set — Thamel Muscle"], img: photos.sports, desc: (n) => `High-performance gym wear for Nepal's growing fitness community. Compression fit, sweat-wicking fabric, and four-way stretch. From CrossFit boxes in Thamel to local gyms across Kathmandu.`, prices: [1200,5500], sizes: ["XS","S","M","L","XL","XXL"], colors: ["neutral","earth"], tags: ["gym","fitness","crossfit","compression","kathmandu"] },
    { slug: "mountain-biking", names: ["MTB Jersey — Mustang Trails","MTB Shorts — Nepal Downhill","Biking Set — Himalayan MTB","Jersey — Annapurna Ride","MTB Gear — Pokhara Trail"], img: photos.sports, desc: (n) => `Mountain biking gear for Nepal's epic trail networks. Reinforced padding, breathable mesh panels, and abrasion-resistant fabric. Designed for the rugged trails of Mustang, Pokhara, and the Kathmandu Valley rim.`, prices: [2500,9500], sizes: ["S","M","L","XL"], colors: ["himalayan","earth","neutral"], tags: ["mtb","mountain-biking","mustang","downhill","trail"] },
    { slug: "climbing-accessories", names: ["Climbing Chalk Bag — Himalayan","Climbing Gloves — Rock Nepal","Climbing Set — Everest Ascent","Chalk Bag — Khumbu Ice","Climbing Gear — Island Peak"], img: photos.trekking, desc: (n) => `Essential climbing accessories for Nepal's mountaineering routes. Chalk bags with Himalayan designs, climbing gloves with grip-enhancing palms, and carabiner sets. Trusted by guides on Island Peak, Mera Peak, and Ama Dablam.`, prices: [800,8500], sizes: ["One Size","S/M","L/XL"], colors: ["earth","neutral","himalayan"], tags: ["climbing","mountaineering","everest","island-peak","chukar"] },
  ],
  KIDS: [
    { slug: "traditional-kids", names: ["Kids Daura — Mini Nepal","Kids Gunyo — Little Festival","Kids Kurta — Junior Heritage","Kids Topi — Small Pride","Kids Cholo — Mini Tradition"], img: photos.kids, desc: (n) => `Adorable traditional Nepali outfits for children. Miniature daura suruwal for boys and gunyo cholo for girls in soft, kid-friendly fabrics. Perfect for Dashain tika, school functions, and family celebrations.`, prices: [1500,5500], sizes: ["2Y","4Y","6Y","8Y","10Y","12Y"], colors: ["festival","red","gold"], tags: ["kids","traditional","dashain","festival","heritage"] },
    { slug: "school-uniform", names: ["School Set — Kathmandu Academy","Uniform — Nepal International","School Shirt — Standard Nepal","Uniform Set — Classic School","School Pants — Nepal Education"], img: photos.kids, desc: (n) => `Durable school uniform sets following Nepal's standard school dress code. White shirt, navy/grey trousers or skirt, and optional sweater. Pre-shrunk cotton-polyester blend that withstands daily wear and frequent washing.`, prices: [800,3500], sizes: ["4Y","6Y","8Y","10Y","12Y","14Y","16Y"], colors: ["neutral","blue"], tags: ["school","uniform","education","kids","durable"] },
    { slug: "kids-tshirt", names: ["Kids Tee — Yeti Adventure","Kids Tee — Nepal Flag","Kids Tee — Mountain Goat","Tee — Little Explorer Nepal","Kids Tee — Rhododendron"], img: photos.kids, desc: (n) => `Colorful graphic t-shirts for kids featuring fun Nepali themes — Yeti, mountains, Nepal flag, rhododendron (national flower), and cute animal designs. 100% organic cotton, pre-shrunk, and machine washable.`, prices: [500,2000], sizes: ["2Y","4Y","6Y","8Y","10Y","12Y"], colors: ["festival","pastel","neutral"], tags: ["kids","t-shirt","graphic","fun","organic-cotton"] },
    { slug: "kids-winter-jacket", names: ["Kids Jacket — Himalayan Puff","Kids Jacket — Nepal Winter","Winter Jacket — Mini Everest","Kids Coat — Kathmandu Cold","Kids Jacket — Snow Friend"], img: photos.wool, desc: (n) => `Warm winter jacket designed for Nepal's chilly winters. Lightweight down alternative fill, water-resistant shell, and fun Himalayan-themed patches. Hooded design with elastic cuffs to keep the cold out.`, prices: [2000,7500], sizes: ["2Y","4Y","6Y","8Y","10Y","12Y"], colors: ["winter","neutral","himalayan"], tags: ["kids","winter","jacket","warm","hooded"] },
    { slug: "kids-party-dress", names: ["Party Dress — Little Princess Nepal","Party Dress — Festival Glam","Dress — Mini Celebration","Party Dress — Tihar Sparkle","Dress — Kids Wedding Guest"], img: photos.fashion, desc: (n) => `Beautiful party dresses for kids' special occasions — weddings, Tihar celebrations, birthdays, and school functions. Soft tulle, satin bows, and subtle sparkle. Comfortable enough for all-day wear.`, prices: [2000,8500], sizes: ["2Y","4Y","6Y","8Y","10Y","12Y"], colors: ["festival","pastel","gold"], tags: ["kids","party","dress","celebration","wedding"] },
    { slug: "kids-shorts", names: ["Kids Shorts — Summer Nepal","Shorts — Kathmandu Play","Kids Shorts — Park Day","Shorts — Pokhara Fun","Kids Shorts — Adventure"], img: photos.cotton, desc: (n) => `Comfortable casual shorts for kids' everyday adventures. Soft cotton jersey, elastic waistband, and fun printed patterns. Perfect for playground time, summer vacations, and running around Kathmandu.`, prices: [400,1800], sizes: ["2Y","4Y","6Y","8Y","10Y","12Y"], colors: ["pastel","neutral","festival"], tags: ["kids","shorts","casual","summer","play"] },
    { slug: "kids-ethnic-outfit", names: ["Ethnic Set — Mini Dashain","Ethnic Outfit — Kids Festival","Kids Set — Little Nepal","Ethnic — Junior Celebration","Kids Set — Heritage Mini"], img: photos.fashion, desc: (n) => `Ethnic outfit sets for kids combining traditional Nepali aesthetics with child-friendly comfort. Dhaka fabric accents, traditional buttons, and vibrant colors. Complete set with top, bottom, and accessories.`, prices: [2000,7500], sizes: ["2Y","4Y","6Y","8Y","10Y","12Y"], colors: ["festival","red","gold"], tags: ["kids","ethnic","traditional","festival","complete-set"] },
  ],
  BABY: [
    { slug: "cashmere-booties", names: ["Baby Booties — Himalayan Soft","Booties — Newborn Cashmere","Baby Booties — Cloud Step","Booties — Little Yeti","Baby Booties — Snow Drop"], img: photos.baby, desc: (n) => `Ultra-soft baby booties made from 100% Himalayan cashmere. Gentle on newborn skin, with non-slip suede soles for early walkers. Hand-knit by artisan mothers in the Kathmandu Valley. The ultimate luxury for little feet.`, prices: [1200,4500], sizes: ["0-6M","6-12M","12-18M","18-24M"], colors: ["pastel","neutral","gold"], tags: ["baby","cashmere","booties","newborn","luxury"] },
    { slug: "organic-onesie", names: ["Organic Onesie — Nepal Baby","Onesie — Kathmandu Organic","Baby Onesie — Soft Cotton","Onesie — Little Sprout Nepal","Baby Onesie — Natural Start"], img: photos.baby, desc: (n) => `GOTS-certified organic cotton onesie for babies. Free from harsh chemicals, dyes, and synthetic materials. Snap closures for easy diaper changes. Designed for Nepal's climate — breathable in summer, warmable in winter.`, prices: [800,3000], sizes: ["0-3M","3-6M","6-12M","12-18M"], colors: ["pastel","neutral"], tags: ["baby","organic","onesie","cotton","gots-certified"] },
    { slug: "knitted-hat", names: ["Baby Hat — Himalayan Beanie","Knitted Hat — Little Cap Nepal","Baby Hat — Warm Earflap","Hat — Newborn Soft","Baby Hat — Mountain Baby"], img: photos.baby, desc: (n) => `Hand-knit baby hat in soft merino wool or cotton blend. Earflap design for extra warmth during Nepal's winter months. Adorable pom-pom on top. Gentle on sensitive baby skin.`, prices: [500,2500], sizes: ["0-6M","6-12M","12-24M"], colors: ["pastel","neutral","winter"], tags: ["baby","hat","knitted","warm","earflap"] },
    { slug: "soft-blanket", names: ["Baby Blanket — Cloud Nepal","Blanket — Himalayan Swaddle","Soft Blanket — Newborn Wrap","Blanket — Kathmandu Cozy","Baby Blanket — Cashmere Soft"], img: photos.baby, desc: (n) => `Incredibly soft baby blanket in cashmere-cotton blend. Generous size for swaddling, stroller cover, or nursery decor. Hypoallergenic and machine washable. Hand-finished edges with subtle traditional pattern border.`, prices: [2000,8500], sizes: ["75x100cm","100x120cm","120x150cm"], colors: ["pastel","neutral","gold"], tags: ["baby","blanket","swaddle","cashmere","hypoallergenic"] },
    { slug: "baby-gift-set", names: ["Gift Set — Welcome Baby Nepal","Gift Set — Newborn Bundle","Baby Gift — Kathmandu Box","Gift Set — Himalayan Welcome","Baby Gift — Little Blessing"], img: photos.baby, desc: (n) => `Beautifully curated baby gift set in a hand-carved wooden box. Includes cashmere booties, organic onesie, knitted hat, and soft blanket. The perfect Pasni (rice-feeding ceremony) or newborn gift. Presentation-ready with traditional blessing card.`, prices: [5000,18000], sizes: ["0-6M","6-12M"], colors: ["pastel","neutral","gold"], tags: ["baby","gift-set","newborn","pasni","presentation-box"] },
    { slug: "baby-wrap", names: ["Baby Wrap — Traditional Nepal","Baby Wrap — Gurkhali Swaddle","Traditional Wrap — Doko Style","Baby Wrap — Nepal Heritage","Wrap — Dhaka Baby Carrier"], img: photos.fabric, desc: (n) => `Traditional Nepali baby wrap inspired by the doko (carrying basket) carrying method used by mothers in rural Nepal. Soft dhaka fabric or cotton blend. Ergonomic design that distributes weight evenly for comfortable babywearing.`, prices: [1500,5500], sizes: ["One Size"], colors: ["festival","earth","neutral"], tags: ["baby","wrap","traditional","doko","babywearing"] },
  ],
  ACCESSORIES: [
    { slug: "pashmina-scarf", names: ["Pashmina Scarf — Kathmandu Classic","Pashmina — Himalayan Wrap","Scarf — Mustang Soft","Pashmina — Pokhara Breeze","Scarf — Everest Light"], img: photos.cashmere, desc: (n) => `Pure Himalayan pashmina scarf in a versatile size for any outfit. Hand-woven with traditional patterns or solid colors. Lightweight warmth that packs flat in any bag. A timeless Nepali accessory.`, prices: [2500,12000], sizes: ["One Size"], colors: ["neutral","earth","winter"], tags: ["pashmina","scarf","cashmere","himalayan","accessory"] },
    { slug: "dhaka-bag", names: ["Dhaka Tote — Kathmandu Carry","Dhaka Bag — Patan Shopper","Dhaka Purse — Traditional Weave","Bag — Nepal Heritage Tote","Dhaka Crossbody — Modern Nepal"], img: photos.fabric, desc: (n) => `Handcrafted tote or crossbody bag in vibrant Dhaka fabric. Lined with cotton, reinforced handles, and interior zip pocket. Perfect for daily use, farmers market runs, or as a unique travel souvenir.`, prices: [800,4500], sizes: ["One Size"], colors: ["festival","red","gold"], tags: ["dhaka","bag","tote","handcrafted","nepali-fabric"] },
    { slug: "handmade-jewelry", names: ["Jewelry — Newari Silver Set","Jewelry — Turquoise Drop Earrings","Jewelry — Coral Pendant","Jewelry — Himalayan Gem Ring","Jewelry — Pote Bracelet"], img: photos.jewelry, desc: (n) => `Handmade jewelry crafted by Newari silversmiths in Patan. Sterling silver with natural turquoise, coral, or amber stones. Each piece carries centuries of metallurgical tradition from the Kathmandu Valley.`, prices: [1200,15000], sizes: ["One Size"], colors: ["gold","earth","festival"], tags: ["jewelry","handmade","newari","silver","turquoise"] },
    { slug: "singing-bowl-set", names: ["Singing Bowl Set — Complete Healing","Bowl Set — Seven Chakra","Singing Bowl — Meditation Kit","Bowl Set — Temple Sound","Singing Bowl — Wellness Pack"], img: photos.traditional, desc: (n) => `Complete singing bowl set with 3-7 bowls tuned to different chakra frequencies. Includes striker, cushion, and instruction guide. Perfect for yoga studios, meditation practice, or sound therapy sessions. Handcrafted near Boudhanath.`, prices: [5000,35000], sizes: ["3 Bowl Set","5 Bowl Set","7 Bowl Set"], colors: ["gold","earth"], tags: ["singing-bowl","meditation","chakra","healing","sound-therapy"] },
    { slug: "prayer-flags", names: ["Prayer Flags — Five Colors","Prayer Flags — Wind Blessing","Flags — Tibetan Blessing Set","Flags — Himalayan Wind","Prayer Flags — Lung Ta"], img: photos.traditional, desc: (n) => `Traditional Tibetan prayer flags in the five sacred colors (blue for sky, white for air, red for fire, green for water, yellow for earth). Printed with mantras and prayers that spread blessings on the wind. Set of 25 or 50 flags on cotton string.`, prices: [500,3500], sizes: ["25 Flags","50 Flags","100 Flags"], colors: ["festival","neutral"], tags: ["prayer-flags","tibetan","buddhist","meditation","blessing"] },
    { slug: "woven-belt", names: ["Woven Belt — Dhaka Waist","Belt — Nepali Traditional","Woven Belt — Patan Weave","Belt — Himalayan Wrap","Woven Belt — Festival Waist"], img: photos.fabric, desc: (n) => `Traditional woven belt in Dhaka or cotton fabric. Adjustable length with hand-woven patterns. Worn with daura suruwal, kurta, or as a stylish accessory for modern outfits.`, prices: [500,3000], sizes: ["S/M","L/XL"], colors: ["festival","red","earth"], tags: ["belt","woven","dhaka","traditional","accessory"] },
    { slug: "hair-accessories", names: ["Hair Clip — Himalayan Bloom","Hair Pin — Lotus Gold","Hair Band — Kathmandu Style","Accessories — Rhododendron Set","Hair Clip — Nepal Floral"], img: photos.jewelry, desc: (n) => `Elegant hair accessories inspired by Nepali flora and temple art. Sterling silver hairpins with lotus and rhododendron motifs, fabric hair bands in Dhaka patterns, and decorative clips for special occasions.`, prices: [300,2500], sizes: ["One Size"], colors: ["gold","festival","pastel"], tags: ["hair","accessories","floral","silver","dhaka"] },
    { slug: "wallet", names: ["Wallet — Dhaka Billfold","Wallet — Hemp Minimal","Wallet — Leather Nepal","Wallet — Allo Slim","Wallet — Kathmandu RFID"], img: photos.leather, desc: (n) => `Handcrafted wallet in Dhaka fabric, hemp, or genuine leather. RFID-blocking layer, multiple card slots, and cash compartment. Compact design that fits in any pocket. Made by artisan partners in Kathmandu.`, prices: [800,4500], sizes: ["One Size"], colors: ["earth","neutral","festival"], tags: ["wallet","dhaka","leather","rfid","handcrafted"] },
    { slug: "phone-case", names: ["Phone Case — Dhaka Pattern","Phone Case — Himalayan Art","Case — Mandala Design","Case — Nepal Flag","Phone Case — Thangka Art"], img: photos.traditional, desc: (n) => `Protective phone case featuring Nepali art — Dhaka patterns, mandala designs, Thangka art, or Nepal flag. Slim profile with raised edges for screen protection. Available for iPhone and Samsung Galaxy models.`, prices: [500,2500], sizes: ["iPhone 15","iPhone 15 Pro","Samsung S24","Pixel 8"], colors: ["festival","earth","neutral"], tags: ["phone-case","dhaka","mandala","protection","nepali-art"] },
    { slug: "sunglasses", names: ["Sunglasses — Himalayan UV","Sunglasses — Everest Shield","Shades — Kathmandu Sun","Sunglasses — Mountain Polarized","Shades — Nepal Adventure"], img: photos.sports, desc: (n) => `Polarized sunglasses designed for Nepal's intense mountain sun. UV400 protection, lightweight frames, and scratch-resistant lenses. Essential for trekking, driving, and daily wear in the Himalayas.`, prices: [1500,6500], sizes: ["One Size"], colors: ["neutral","earth"], tags: ["sunglasses","polarized","uv-protection","trekking","mountain"] },
  ],
  HOME: [
    { slug: "handwoven-rug", names: ["Handwoven Rug — Tibetan Knot","Rug — Himalayan Wool","Rug — Kathmandu Floor","Rug — Mandala Weave","Handwoven Rug — Lotus Design"], img: photos.home, desc: (n) => `Hand-knotted Tibetan-style rug made from Himalayan sheep wool. 80-100 knots per square inch for exceptional durability and detail. Traditional mandala, lotus, or geometric patterns. Natural dyes on a cotton foundation.`, prices: [5000,45000], sizes: ["60x90cm","90x150cm","120x180cm","150x240cm","200x300cm"], colors: ["earth","red","gold","neutral"], tags: ["rug","handwoven","tibetan","wool","home-decor"] },
    { slug: "dhaka-cushion", names: ["Dhaka Cushion — Patan Pillow","Cushion Cover — Nepal Weave","Cushion — Geometric Dhaka","Cover — Kathmandu Home","Cushion — Bhaktapur Pattern"], img: photos.home, desc: (n) => `Decorative cushion cover in authentic hand-woven Dhaka fabric. Vibrant geometric patterns that add a touch of Nepal to any living space. Hidden zipper, fits standard cushion inserts. Machine washable.`, prices: [500,2500], sizes: ["40x40cm","45x45cm","50x50cm"], colors: ["festival","red","gold"], tags: ["cushion","dhaka","home-decor","living-room","handwoven"] },
    { slug: "cashmere-throw", names: ["Cashmere Throw — Everest Cozy","Throw — Himalayan Blanket","Throw — Kathmandu Lounge","Cashmere — Mustang Comfort","Throw — Pokhara Evening"], img: photos.cashmere, desc: (n) => `Luxurious cashmere throw blanket for sofa or bed. 100% Himalayan cashmere in generous throw dimensions. Incredibly soft and warm — the perfect companion for chilly Kathmandu evenings or mountain lodge relaxation.`, prices: [8000,35000], sizes: ["130x170cm","150x200cm","180x220cm"], colors: ["neutral","earth","winter"], tags: ["cashmere","throw","blanket","luxury","home"] },
    { slug: "thangka-wall-art", names: ["Thangka Print — Buddha Wisdom","Wall Art — Mandala Canvas","Thangka — Compassion Gold","Wall Art — Tara Framed","Thangka Print — Wheel of Dharma"], img: photos.traditional, desc: (n) => `High-quality Thangka art prints on premium canvas or archival paper. Museum-grade reproduction of centuries-old Tibetan Buddhist paintings. Available framed or unframed. Brings serenity and spiritual depth to any space.`, prices: [1500,15000], sizes: ["30x40cm","40x60cm","60x90cm","Framed 40x60cm"], colors: ["gold","earth","neutral"], tags: ["thangka","wall-art","buddhist","mandala","framed"] },
    { slug: "singing-bowl-home", names: ["Singing Bowl Set — Home Meditation","Bowl — Living Room Zen","Singing Bowl — Desk Peace","Bowl Set — Mindful Home","Singing Bowl — Family Calm"], img: photos.traditional, desc: (n) => `Curated singing bowl set for home meditation and relaxation. Includes 2-3 bowls in complementary frequencies, striker, cushion, and a beautifully illustrated guide to sound therapy. Creates a peaceful atmosphere in any room.`, prices: [3500,18000], sizes: ["2 Bowl Set","3 Bowl Set","Deluxe Set"], colors: ["gold","earth"], tags: ["singing-bowl","home","meditation","relaxation","zen"] },
    { slug: "incense-holder", names: ["Incense Holder — Brass Lotus","Incense Holder — Wood Carved","Holder — Temple Design","Incense — Himalayan Stand","Holder — Copper Om"], img: photos.traditional, desc: (n) => `Handcrafted incense holder in brass, copper, or carved wood. Lotus, Om, or mandala designs inspired by Nepali temple architecture. Catches ash neatly. Fits standard stick and cone incense.`, prices: [500,3500], sizes: ["One Size"], colors: ["gold","earth","neutral"], tags: ["incense","holder","brass","temple","meditation"] },
    { slug: "carved-wooden-box", names: ["Wooden Box — Newari Carved","Box — Bhaktapur Craft","Wooden Box — Jewelry Storage","Box — Nepal Keepsake","Wooden Box — Temple Design"], img: photos.wooden, desc: (n) => `Hand-carved wooden storage box by Newari artisans in Bhaktapur. Intricate floral and geometric patterns on the lid. Brass latch and hinges. Perfect for jewelry, keepsakes, or as a decorative piece.`, prices: [1500,8500], sizes: ["Small","Medium","Large","Extra Large"], colors: ["earth","neutral"], tags: ["wooden-box","carved","newari","storage","handcrafted"] },
    { slug: "tea-set", names: ["Tea Set — Himalayan Ceramic","Tea Set — Nepal Porcelain","Tea Set — Mountain Brew","Set — Ilam Tea Ceremony","Tea Set — Kathmandu Pour"], img: photos.home, desc: (n) => `Elegant tea set inspired by Nepal's Ilam tea culture. Handmade ceramic teapot with 4-6 cups in earthy Himalayan tones. Perfect for brewing Nepali orthodox tea or Tibetan butter tea. Gift-boxed presentation.`, prices: [2000,12000], sizes: ["Teapot + 4 Cups","Teapot + 6 Cups","Deluxe Set"], colors: ["earth","neutral"], tags: ["tea-set","ceramic","ilam","nepali-tea","gift"] },
    { slug: "meditation-cushion", names: ["Meditation Cushion — Zafu Nepal","Cushion — Lotus Seat","Meditation — Buckwheat Fill","Cushion — Boudha Sit","Meditation Cushion — Dharma Seat"], img: photos.home, desc: (n) => `Traditional meditation cushion (zafu) filled with organic buckwheat hulls. Removable dhaka fabric or cotton cover. Ergonomic shape supports proper posture during meditation. Inspired by cushions used at Boudhanath monasteries.`, prices: [1500,5500], sizes: ["Standard","Large"], colors: ["earth","neutral","festival"], tags: ["meditation","cushion","zafu","buckwheat","boudhanath"] },
    { slug: "tapestry", names: ["Tapestry — Mandala Wall","Tapestry — Himalayan Scene","Tapestry — Buddha Cotton","Wall Hanging — Nepal Art","Tapestry — Tibetan Dream"], img: photos.home, desc: (n) => `Large cotton tapestry featuring mandala, Himalayan landscape, or Buddhist art designs. Screen-printed with natural dyes. Versatile as wall hanging, bedspread, or picnic blanket. Adds bohemian Nepal vibes to any space.`, prices: [800,5500], sizes: ["150x210cm","210x240cm","240x260cm"], colors: ["festival","earth","neutral"], tags: ["tapestry","wall-hanging","mandala","bohemian","cotton"] },
  ],
  ELECTRONICS: [
    { slug: "phone-accessories", names: ["Phone Case — Nepal Shield","Charger — Himalayan Fast","Cable — Kathmandu Connect","Screen Guard — Everest Protect","Pop Socket — Nepal Grip"], img: photos.electronics, desc: (n) => `Essential phone accessories for the connected Nepali. Durable cases with Himalayan designs, fast chargers, braided cables, and tempered glass screen protectors. Quality-tested for Nepal's dust and humidity conditions.`, prices: [300,2500], sizes: ["One Size"], colors: ["neutral","earth"], tags: ["phone","accessories","charger","case","cable"] },
    { slug: "headphones", names: ["Headphones — Himalayan Sound","Earbuds — Kathmandu Bass","Headphones — Nepal Wireless","Earbuds — Noise Cancel Nepal","Headphones — Studio Pro"], img: photos.electronics, desc: (n) => `Quality headphones and earbuds for music, calls, and meditation. Bluetooth 5.3, active noise cancellation, and 24-hour battery life. Perfect for commutes on Kathmandu buses or focus during remote work.`, prices: [1500,12000], sizes: ["One Size"], colors: ["neutral","earth"], tags: ["headphones","earbuds","bluetooth","noise-cancel","music"] },
    { slug: "smartwatch", names: ["Smartwatch — Nepal Fit","Watch — Himalayan Track","Smartwatch — Kathmandu Health","Watch — Everest Monitor","Smartwatch — Nepal Active"], img: photos.electronics, desc: (n) => `Feature-rich smartwatch with heart rate, SpO2, GPS, and 7-day battery. Water-resistant for Nepal's monsoon. Tracks steps, sleep, and altitude — perfect for trekking and daily fitness. Compatible with iOS and Android.`, prices: [3000,15000], sizes: ["One Size"], colors: ["neutral","earth"], tags: ["smartwatch","fitness","gps","heart-rate","altitude"] },
    { slug: "portable-speaker", names: ["Speaker — Himalayan Bass","Speaker — Nepal Portable","Speaker — Kathmandu Sound","Speaker — Trek Music","Speaker — Waterproof Nepal"], img: photos.electronics, desc: (n) => `Portable Bluetooth speaker with powerful bass and 12-hour battery. Waterproof and dustproof — built for Nepal's outdoors. Compact enough for trekking, loud enough for garden parties in Kathmandu.`, prices: [1500,8500], sizes: ["One Size"], colors: ["neutral","earth"], tags: ["speaker","bluetooth","portable","waterproof","bass"] },
    { slug: "power-bank", names: ["Power Bank — Everest Charge","Power Bank — Nepal 20000mAh","Power Bank — Solar Trek","Power Bank — Fast Charge Nepal","Power Bank — Mini Portable"], img: photos.electronics, desc: (n) => `High-capacity power bank for Nepal's power outages and trekking trips. 10,000-20,000mAh with fast charging, dual USB ports, and LED indicator. Solar option available for multi-day treks.`, prices: [1200,5500], sizes: ["10000mAh","20000mAh","Solar 20000mAh"], colors: ["neutral"], tags: ["power-bank","charging","solar","trekking","portable"] },
    { slug: "led-lights", names: ["LED Strip — Nepal Glow","LED Lamp — Himalayan Bright","LED — Kathmandu Room","LED — Festival Decoration","LED — Emergency Nepal"], img: photos.electronics, desc: (n) => `Energy-efficient LED lights for home and festival decoration. RGB color-changing strips, warm white bulbs, and emergency backup lamps. Low power consumption — perfect for Nepal's energy-conscious households.`, prices: [500,4500], sizes: ["1m","3m","5m","Bulb Pack"], colors: ["neutral","festival"], tags: ["led","lights","energy-efficient","festival","home"] },
    { slug: "usb-cables", names: ["USB-C — Nepal Fast Charge","Cable Set — Kathmandu Kit","Lightning — Apple Nepal","USB Cable — Braided Durable","Cable — Multi-Connector"], img: photos.electronics, desc: (n) => `Durable braided USB cables in USB-C, Lightning, and Micro-USB. Nylon braiding for extra strength — survives Nepal's daily commute wear and tear. Fast charging and data sync supported.`, prices: [300,1500], sizes: ["1m","2m","3m","Multi Pack"], colors: ["neutral"], tags: ["usb","cable","charging","braided","durable"] },
  ],
  BEAUTY: [
    { slug: "himalayan-salt-soap", names: ["Salt Soap — Pink Himalayan","Soap — Khumbal Natural","Soap — Himalayan Mineral","Soap — Nepal Detox","Soap — Mountain Pure"], img: photos.beauty, desc: (n) => `Handmade soap infused with genuine pink Himalayan salt from Khumbal mines. Natural exfoliation, mineral-rich, and deeply cleansing. Cold-process method preserves natural glycerin. No artificial colors or fragrances.`, prices: [300,1500], sizes: ["100g","200g","Gift Set of 3"], colors: ["neutral","earth"], tags: ["soap","himalayan-salt","natural","exfoliating","handmade"] },
    { slug: "essential-oils", names: ["Essential Oil — Nepal Rhododendron","Oil — Himalayan Lavender","Oil — Juniper Nepal","Essential Oil — Timur Spice","Oil — Citronella Kathmandu"], img: photos.beauty, desc: (n) => `Pure essential oils steam-distilled from Nepal's botanical treasures — rhododendron, juniper, timur (Sichuan pepper), and citronella. Therapeutic grade for aromatherapy, massage, and diffuser use.`, prices: [800,4500], sizes: ["10ml","30ml","50ml"], colors: ["earth","neutral"], tags: ["essential-oil","aromatherapy","rhododendron","juniper","natural"] },
    { slug: "herbal-face-mask", names: ["Face Mask — Turmeric Nepal","Mask — Himalayan Clay","Face Mask — Sandalwood Glow","Mask — Multani Nepal","Face Mask — Ayurvedic Glow"], img: photos.beauty, desc: (n) => `Traditional Ayurvedic face mask with Himalayan herbs — turmeric, sandalwood, neem, and multani mitti (Fuller's earth). Deep cleansing, brightening, and oil-balancing. Mixed with water or honey for a spa-quality treatment at home.`, prices: [500,2500], sizes: ["50g","100g","200g"], colors: ["earth","neutral"], tags: ["face-mask","turmeric","ayurvedic","herbal","brightening"] },
    { slug: "lip-balm", names: ["Lip Balm — Himalayan Honey","Lip Balm — Beeswax Nepal","Lip Balm — Rhododendron Tint","Balm — Shea Butter Nepal","Lip Balm — Mint Fresh Kathmandu"], img: photos.beauty, desc: (n) => `Nourishing lip balm with Himalayan beeswax, shea butter, and natural essential oils. Protects lips from Kathmandu's dry winter air and mountain winds. Subtle rhododendron tint available.`, prices: [200,800], sizes: ["4.5g","Pack of 3"], colors: ["neutral","pastel"], tags: ["lip-balm","beeswax","himalayan","moisturizing","natural"] },
    { slug: "hair-oil", names: ["Hair Oil — Amla Nepal","Hair Oil — Coconut Himalayan","Hair Oil — Bhringraj Growth","Oil — Aromatic Kathmandu","Hair Oil — Coconut Nepal"], img: photos.beauty, desc: (n) => `Traditional Nepali hair oil infused with amla (Indian gooseberry), bhringraj, and coconut oil. Promotes hair growth, reduces dandruff, and adds natural shine. Used for centuries in Ayurvedic hair care.`, prices: [400,2000], sizes: ["100ml","200ml","500ml"], colors: ["earth","neutral"], tags: ["hair-oil","amla","bhringraj","ayurvedic","growth"] },
    { slug: "natural-perfume", names: ["Perfume — Himalayan Musk","Perfume — Nepal Jasmine","Perfume — Temple Sandalwood","Perfume — Mountain Rose","Perfume — Kathmandu Night"], img: photos.beauty, desc: (n) => `Natural perfume oil crafted from Himalayan botanicals — jasmine, sandalwood, rose, and musk notes. Alcohol-free, long-lasting, and gentle on skin. Applied to pulse points for an all-day subtle fragrance.`, prices: [1200,6500], sizes: ["10ml","30ml","50ml"], colors: ["neutral","earth","gold"], tags: ["perfume","natural","alcohol-free","himalayan","fragrance"] },
    { slug: "skincare-set", names: ["Skincare Set — Nepal Glow","Skincare — Himalayan Routine","Set — Kathmandu Beauty","Skincare Set — Ayurvedic Complete","Set — Nepal Radiance"], img: photos.beauty, desc: (n) => `Complete skincare routine set with Himalayan ingredients — cleanser, toner, serum, and moisturizer. All-natural, cruelty-free, and packaged in recyclable materials. The Nepal glow in one beautifully curated box.`, prices: [3000,15000], sizes: ["Travel Set","Full Set","Deluxe Set"], colors: ["neutral","pastel","earth"], tags: ["skincare","set","natural","ayurvedic","gift"] },
  ],
  FOOD: [
    { slug: "himalayan-tea", names: ["Himalayan Tea — Ilam Orthodox","Tea — Nepal Golden Tip","Tea — Ilam Green","Tea — Kanchanjangha Premium","Tea — Nepal Breakfast Blend"], img: photos.food, desc: (n) => `Premium orthodox tea from the tea gardens of Ilam, eastern Nepal. Grown at 1,500-2,000m elevation with a clean, floral character. Single-origin, hand-plucked, and traditionally processed. The taste of the Himalayas in every cup.`, prices: [500,3500], sizes: ["50g","100g","250g","500g"], colors: ["earth","neutral"], tags: ["tea","himalayan","ilam","orthodox","organic"] },
    { slug: "organic-honey", names: ["Organic Honey — Himalayan Cliff","Honey — Mad Honey Nepal","Honey — Wild Flower Nepal","Honey — Mustang Raw","Honey — Terai Pure"], img: photos.food, desc: (n) => `Raw, unprocessed Himalayan honey collected from wild cliff hives in the Gurung villages of central Nepal. Rich in antioxidants and enzymes. Some varieties include the famous "mad honey" (madhu) from rhododendron nectar.`, prices: [800,8500], sizes: ["250g","500g","1kg"], colors: ["earth","gold"], tags: ["honey","organic","himalayan","raw","wild"] },
    { slug: "spice-blends", names: ["Spice Blend — Momo Masala","Spice Blend — Dal Bhat Masala","Spice — Nepal Curry Mix","Spice Blend — Chatpide","Spice — Timura Blend"], img: photos.food, desc: (n) => `Authentic Nepali spice blends hand-ground from whole spices sourced across Nepal and the Terai. Momo masala for dumplings, dal bhat masala for everyday meals, and chatpide for that signature Nepali tang.`, prices: [300,2000], sizes: ["50g","100g","200g"], colors: ["earth","festival"], tags: ["spice","masala","nepali","cooking","momo"] },
    { slug: "momo-kit", names: ["Momo Kit — Complete DIY","Momo Kit — Chicken Fillings","Momo Kit — Veggie Deluxe","Momo Kit — Family Pack","Momo Kit — Spicy Challenge"], img: photos.food, desc: (n) => `Everything you need to make authentic Nepali momos at home — pre-mixed flour for wrappers, spice blend for filling, and achaar (dipping sauce) mix. Choose chicken, buff, or vegetable. Makes 50+ momos. Family fun night, Nepali style.`, prices: [500,2500], sizes: ["2-Person","4-Person","Family Pack"], colors: ["earth"], tags: ["momo","dumpling","diy","kit","nepali-food"] },
    { slug: "sel-roti-mix", names: ["Sel Roti Mix — Tihar Special","Sel Roti — Dashain Sweet","Sel Roti Mix — Festival Ready","Sel Roti — Traditional Rice","Sel Roti Mix — Nepal Sweet"], img: photos.food, desc: (n) => `Pre-mixed Sel Roti flour blend for Nepal's iconic ring-shaped bread. Just add water, yogurt, and banana. Perfect for Tihar, Dashain, and everyday breakfast. Traditional recipe from the hills of Nepal.`, prices: [300,1200], sizes: ["500g","1kg","2kg"], colors: ["earth"], tags: ["sel-roti","tihar","dashain","sweet","festival-food"] },
    { slug: "pickles", names: ["Pickle — Timur Achaar","Pickle — Mango Nepal","Pickle — Bamboo Shoot","Pickle — Radish Tikha","Pickle — Mixed Achaar"], img: photos.food, desc: (n) => `Traditional Nepali pickles (achaar) made with sun-dried vegetables and Himalayan timur pepper. Spicy, tangy, and addictive. Perfect companion to dal bhat, momos, or as a snack with beaten rice (chiura).`, prices: [200,1200], sizes: ["200g","400g","750g"], colors: ["earth","festival"], tags: ["pickle","achaar","timur","spicy","nepali"] },
    { slug: "dried-fruits", names: ["Dried Fruits — Himalayan Mix","Dried Fruits — Walnut Nepal","Dried Fruits — Apricot Mustang","Dried Fruits — Trail Mix Nepal","Dried Fruits — Energy Pack"], img: photos.food, desc: (n) => `Premium dried fruits and nuts sourced from Nepal's mountain valleys — Mustang apricots, Walnuts from Dolpo, and Himalayan trail mix. Perfect for trekking snacking, baking, or healthy gifting.`, prices: [500,4500], sizes: ["100g","250g","500g","1kg"], colors: ["earth","gold"], tags: ["dried-fruits","walnut","apricot","trail-mix","healthy"] },
  ],
};

// ─── Product generation ─────────────────────────────────────────────
function generateProducts(categoryName, defs, startIndex = 0) {
  const products = [];
  let idx = startIndex;
  for (const def of defs) {
    const count = def.names.length;
    for (let i = 0; i < count; i++) {
      const photoId = pick(def.img);
      const price = rand(def.prices[0], def.prices[1]);
      const colorKey = pick(def.colors);
      const product = {
        id: `${categoryName.toLowerCase()}-${idx}`,
        name: def.names[i],
        description: def.desc(def.names[i]),
        price,
        category: categoryName,
        image: img(photoId),
        sizes: def.sizes,
        colors: COLORS[colorKey] || COLORS.neutral,
        isNew: isNew(idx, defs.reduce((s, d) => s + d.names.length, 0)),
        rating: rating(),
        reviews: reviews(),
        stock: stock(),
        sold: sold(),
        freeShipping: freeShipping(price),
        shippingFrom: "Nepal",
        tags: def.tags || [categoryName.toLowerCase(), def.slug],
      };
      products.push(product);
      idx++;
    }
  }
  return products;
}

// ─── Generate all categories ────────────────────────────────────────
const allProducts = [];
const categoryKeys = Object.keys(catalogDefs);
let globalIdx = 0;

for (const cat of categoryKeys) {
  const products = generateProducts(cat, catalogDefs[cat], globalIdx);
  allProducts.push(...products);
  globalIdx += products.length;
  console.log(`  ${cat}: ${products.length} products`);
}

console.log(`\nTotal products generated: ${allProducts.length}`);

// ─── Write products.json ────────────────────────────────────────────
const publicDir = path.join(__dirname, "public");
if (!fs.existsSync(publicDir)) fs.mkdirSync(publicDir, { recursive: true });
fs.writeFileSync(path.join(publicDir, "products.json"), JSON.stringify(allProducts, null, 2));
console.log(`Wrote public/products.json`);

// ─── Generate traditional.json ──────────────────────────────────────
const traditionalDefs = [
  { name: "Daura Suruwal Classic", price: 8500, img: "1594938298603", desc: "Handwoven cotton daura suruwal with subtle gold thread detailing. Traditional Nepali formal wear reimagined for modern occasions.", colors: COLORS.neutral, sizes: ["S","M","L","XL","XXL"] },
  { name: "Gunyo Cholo Heritage", price: 6200, img: "1610030469983", desc: "Authentic hand-stitched gunyo cholo in vibrant crimson silk. A timeless symbol of Nepali femininity with intricate border embroidery.", colors: COLORS.red, sizes: ["XS","S","M","L","XL"] },
  { name: "Sari Banarasi Gold", price: 15000, img: "1617627143750", desc: "Luxurious Banarasi silk sari with real zari work. Woven on traditional handlooms in Varanasi style with Nepali motifs.", colors: COLORS.gold, sizes: ["One Size"] },
  { name: "Dhaka Topi Premium", price: 1800, img: "1598300042247", desc: "Hand-loomed dhaka fabric topi with geometric patterns. Nepal's iconic national headwear in premium quality.", colors: COLORS.festival, sizes: ["S","M","L","XL"] },
  { name: "Haku Patasi Newari", price: 12000, img: "1583391733956", desc: "Traditional Newari black sari with red border. Handwoven cotton with authentic patasi design from Bhaktapur.", colors: COLORS.neutral, sizes: ["One Size"] },
  { name: "Bhadrain Coat Formal", price: 9500, img: "1594938298603", desc: "Elegant formal bhadrain coat in premium wool blend. Structured shoulders with traditional Nepali collar design.", colors: COLORS.neutral, sizes: ["S","M","L","XL","XXL"] },
  { name: "Kurtha Suruwal Linen", price: 4500, img: "1594938298603", desc: "Breathable linen kurtha suruwal for everyday comfort. Minimalist design with traditional side slits and mother-of-pearl buttons.", colors: COLORS.neutral, sizes: ["S","M","L","XL"] },
  { name: "Cholo Blouse Silk", price: 3800, img: "1610030469983", desc: "Fitted silk cholo blouse with traditional hook-and-eye closure. Intricate hand-embroidered neckline in gold thread.", colors: COLORS.gold, sizes: ["XS","S","M","L"] },
  { name: "Pashmina Shawl Kasmir", price: 18000, img: "1434387367598", desc: "100% pure pashmina shawl from the Himalayan highlands. Ultra-soft hand-woven wrap with traditional paisley motifs.", colors: COLORS.earth, sizes: ["One Size"] },
  { name: "Suruwal Trouser Classic", price: 2800, img: "1624378439575", desc: "Traditional tapered suruwal trousers in lightweight cotton. Elasticated waist with drawstring and side pockets.", colors: COLORS.neutral, sizes: ["S","M","L","XL","XXL"] },
  { name: "Weston Waistcoat", price: 4200, img: "1594938298603", desc: "Traditional Nepali weston waistcoat in brocade fabric. Five-button closure with silk lining and embroidered pockets.", colors: COLORS.gold, sizes: ["S","M","L","XL"] },
  { name: "Lehenga Choli Bridal", price: 35000, img: "1595777457583", desc: "Stunning bridal lehenga choli in heavy silk with sequin and zardozi work. Full circular skirt with matching dupatta.", colors: COLORS.red, sizes: ["S","M","L"] },
  { name: "Topi Cap Dhaka Weave", price: 2200, img: "1598300042247", desc: "Premium dhaka topi with intricate woven pattern. Stiffened crown with sweatband lining for comfortable all-day wear.", colors: COLORS.festival, sizes: ["S","M","L","XL"] },
  { name: "Sari Cotton Handloom", price: 3500, img: "1617627143750", desc: "Everyday cotton handloom sari from eastern Nepal. Soft drape with traditional check pattern and contrasting pallu.", colors: COLORS.red, sizes: ["One Size"] },
  { name: "Daura Double-Breasted", price: 11000, img: "1594938298603", desc: "Premium double-breasted daura in fine wool. Eight traditional tie-strings (pattuka) with reinforced collar and cuffs.", colors: COLORS.neutral, sizes: ["S","M","L","XL","XXL"] },
  { name: "Patuka Waist Sash", price: 1500, img: "1434387367598", desc: "Traditional woven patuka waist sash in vibrant cotton. Multi-purpose wrap providing back support and style.", colors: COLORS.red, sizes: ["One Size"] },
  { name: "Khukuri Pendant Silver", price: 2800, img: "1535632066927", desc: "Sterling silver khukuri-shaped pendant with traditional engraving. Comes on a hand-braided cord with adjustable length.", colors: COLORS.neutral, sizes: ["One Size"] },
  { name: "Shawl Dhaka Border", price: 5500, img: "1434387367598", desc: "Wide dhaka-bordered shawl in soft merino wool. Perfect for mountain evenings and formal traditional gatherings.", colors: COLORS.neutral, sizes: ["One Size"] },
  { name: "Bhaktapur Jewelry Set", price: 8500, img: "1535632066927", desc: "Handcrafted jewelry set inspired by Newari temple art. Includes necklace, earrings, and maang tikka in brass with gold plating.", colors: COLORS.gold, sizes: ["One Size"] },
  { name: "Tibetan Chuba Wool", price: 14000, img: "1594938298603", desc: "Authentic Tibetan-style chuba in thick hand-spun wool. Warm full-length robe with contrasting sleeve cuffs and sash.", colors: COLORS.earth, sizes: ["M","L","XL","XXL"] },
  { name: "Kurtha Mandarin Collar", price: 5200, img: "1624378439575", desc: "Modern kurtha with mandarin collar and hidden placket. Slim-fit design in breathable cotton-silk blend.", colors: COLORS.blue, sizes: ["S","M","L","XL"] },
  { name: "Sari Organza Floral", price: 7800, img: "1617627143750", desc: "Light organza sari with hand-painted floral motifs. Perfect for spring festivals and daytime celebrations.", colors: COLORS.pastel, sizes: ["One Size"] },
  { name: "Dhaka Fabric by Meter", price: 800, img: "1598300042247", desc: "Premium dhaka fabric sold by the meter. Vibrant geometric weave for custom tailoring of topis, coats, and accessories.", colors: COLORS.festival, sizes: ["1m","2m","3m","5m"] },
  { name: "Lungi Cotton Check", price: 900, img: "1624378439575", desc: "Comfortable cotton lungi in traditional check pattern. Soft pre-washed fabric with reinforced hem for daily wear.", colors: COLORS.red, sizes: ["One Size"] },
  { name: "Bridal Chura Set", price: 4500, img: "1595777457583", desc: "Traditional red and white bridal chura (bangle) set with gold filigree. Comes in ornate wooden box with velvet lining.", colors: COLORS.red, sizes: ["One Size"] },
];

const traditionalProducts = traditionalDefs.map((t, i) => ({
  id: `traditional-${i}`,
  name: t.name,
  description: t.desc,
  price: t.price,
  category: "TRADITIONAL",
  image: img(t.img),
  sizes: t.sizes,
  colors: t.colors,
  isNew: i < 6,
  rating: (4.2 + Math.random() * 0.8).toFixed(1),
  reviews: rand(40, 350),
  stock: stock(),
  sold: sold(),
  freeShipping: freeShipping(t.price),
  shippingFrom: "Nepal",
  tags: ["traditional", "heritage", "nepali", "handcrafted"],
}));

fs.writeFileSync(path.join(publicDir, "traditional.json"), JSON.stringify(traditionalProducts, null, 2));
console.log(`Wrote public/traditional.json (${traditionalProducts.length} products)`);

// ─── Generate marketplace.json ──────────────────────────────────────
const marketplaceDefs = [
  // Electronics (15)
  { cat: "ELECTRONICS", slug: "wireless-earbuds-pro", name: "Wireless Earbuds Pro — Nepal Bass", price: 2500, img: "1505784704326", desc: "True wireless earbuds with deep bass tuning for Nepali music. Bluetooth 5.3, 24hr case battery, IPX5 water resistance.", sizes: ["One Size"], tags: ["electronics","earbuds","bluetooth","bass","wireless"] },
  { cat: "ELECTRONICS", slug: "smart-band-fitness", name: "Smart Band — Himalayan Fit", price: 1800, img: "1546878649355", desc: "Fitness tracker band with heart rate, steps, and sleep monitoring. Water-resistant band for Nepal's monsoon. 7-day battery.", sizes: ["One Size"], tags: ["electronics","fitness","tracker","smart-band","heart-rate"] },
  { cat: "ELECTRONICS", slug: "usb-hub-multiport", name: "USB Hub — Kathmandu Connect", price: 1200, img: "1523275335684", desc: "7-in-1 USB-C hub for laptops. HDMI, USB 3.0, SD card reader, and PD charging. Essential for remote workers in Nepal.", sizes: ["One Size"], tags: ["electronics","usb","hub","laptop","connectivity"] },
  { cat: "ELECTRONICS", slug: "phone-gimbal", name: "Phone Gimbal — Nepal Creator", price: 5500, img: "1583391733956", desc: "3-axis phone gimbal for smooth vlogging and content creation. Face tracking, gesture control, and 12hr battery.", sizes: ["One Size"], tags: ["electronics","gimbal","vlogging","creator","stabilizer"] },
  { cat: "ELECTRONICS", slug: "solar-charger", name: "Solar Charger — Everest Sun", price: 3500, img: "1523275335684", desc: "Foldable solar panel charger for trekking. 20W output, dual USB, lightweight. Charges phones from the Himalayan sun.", sizes: ["One Size"], tags: ["electronics","solar","charger","trekking","everest"] },
  { cat: "ELECTRONICS", slug: "webcam-hd", name: "Webcam HD — Nepal Remote", price: 2800, img: "1583391733956", desc: "1080p webcam with auto-focus and built-in microphone. Plug-and-play for Zoom, Meet, and online classes in Nepal.", sizes: ["One Size"], tags: ["electronics","webcam","remote-work","1080p","zoom"] },
  { cat: "ELECTRONICS", slug: "mechanical-keyboard", name: "Mechanical Keyboard — Nepal Type", price: 4500, img: "1523275335684", desc: "Compact 75% mechanical keyboard with hot-swappable switches. RGB backlighting, PBT keycaps, USB-C connection.", sizes: ["One Size"], tags: ["electronics","keyboard","mechanical","gaming","typing"] },
  { cat: "ELECTRONICS", slug: "laptop-stand", name: "Laptop Stand — Ergonomic Nepal", price: 1800, img: "1583391733956", desc: "Adjustable aluminum laptop stand for ergonomic working. Foldable, portable, and compatible with all laptop sizes.", sizes: ["One Size"], tags: ["electronics","laptop-stand","ergonomic","portable","aluminum"] },
  { cat: "ELECTRONICS", slug: "mini-projector", name: "Mini Projector — Nepal Cinema", price: 8500, img: "1523275335684", desc: "Portable mini projector for home entertainment. 1080p support, built-in speaker, 2hr battery. Movie nights in Kathmandu.", sizes: ["One Size"], tags: ["electronics","projector","portable","home-cinema","entertainment"] },
  { cat: "ELECTRONICS", slug: "smart-plug", name: "Smart Plug — Nepal Home", price: 800, img: "1583391733956", desc: "WiFi smart plug with app control and scheduling. Monitor energy usage, set timers. Works with Google Home and Alexa.", sizes: ["One Size"], tags: ["electronics","smart-plug","wifi","home-automation","energy"] },
  { cat: "ELECTRONICS", slug: "dash-cam", name: "Dash Cam — Kathmandu Drive", price: 4200, img: "1523275335684", desc: "1080p dash cam with night vision and loop recording. G-sensor for incident detection. Essential for Kathmandu traffic.", sizes: ["One Size"], tags: ["electronics","dash-cam","driving","kathmandu","safety"] },
  { cat: "ELECTRONICS", slug: "wireless-mouse", name: "Wireless Mouse — Nepal Ergo", price: 1200, img: "1583391733956", desc: "Ergonomic wireless mouse with silent clicks. 2.4GHz + Bluetooth dual mode, 12-month battery life.", sizes: ["One Size"], tags: ["electronics","mouse","wireless","ergonomic","silent"] },
  { cat: "ELECTRONICS", slug: "bluetooth-adapter", name: "Bluetooth Adapter — Nepal Connect", price: 600, img: "1523275335684", desc: "USB Bluetooth 5.0 adapter for PC/laptop. Connect headphones, keyboards, and speakers wirelessly.", sizes: ["One Size"], tags: ["electronics","bluetooth","adapter","usb","wireless"] },
  { cat: "ELECTRONICS", slug: "phone-tripod", name: "Phone Tripod — Nepal Creator", price: 1500, img: "1583391733956", desc: "Extendable phone tripod with Bluetooth remote. 1.2m max height, flexible legs, and 360-degree phone mount.", sizes: ["One Size"], tags: ["electronics","tripod","phone","vlogging","photography"] },
  { cat: "ELECTRONICS", slug: "cable-organizer", name: "Cable Organizer — Nepal Tidy", price: 400, img: "1523275335684", desc: "Silicone cable management clips and sleeves. Keep your desk and travel bag organized. Set of 10 pieces.", sizes: ["One Size"], tags: ["electronics","cable","organizer","desk","travel"] },

  // Beauty (15)
  { cat: "BEAUTY", slug: "sunscreen-spf50", name: "Sunscreen SPF50 — Nepal Shield", price: 800, img: "1596462906757", desc: "Broad-spectrum SPF50 sunscreen for Nepal's intense UV at altitude. Lightweight, non-greasy, reef-safe.", sizes: ["50ml","100ml"], tags: ["beauty","sunscreen","spf50","uv-protection","outdoor"] },
  { cat: "BEAUTY", slug: "face-serum-vitamin-c", name: "Face Serum — Himalayan Glow", price: 1500, img: "1571786183568", desc: "Vitamin C face serum with Himalayan botanicals. Brightens, evens skin tone, and fights pollution damage from Kathmandu air.", sizes: ["30ml","50ml"], tags: ["beauty","serum","vitamin-c","brightening","himalayan"] },
  { cat: "BEAUTY", slug: "shampoo-herbal", name: "Shampoo — Nepal Herbal", price: 600, img: "1556228578", desc: "Sulfate-free herbal shampoo with amla, shikakai, and reetha. Traditional Nepali hair washing ingredients in a modern formula.", sizes: ["200ml","400ml","750ml"], tags: ["beauty","shampoo","herbal","amla","sulfate-free"] },
  { cat: "BEAUTY", slug: "body-lotion-shea", name: "Body Lotion — Himalayan Moisture", price: 700, img: "1598448794320", desc: "Rich body lotion with shea butter, Himalayan honey, and almond oil. Deep hydration for Nepal's dry winter months.", sizes: ["200ml","400ml"], tags: ["beauty","body-lotion","shea-butter","moisturizing","winter"] },
  { cat: "BEAUTY", slug: "kajal-eyeliner", name: "Kajal Eyeliner — Nepal Kohl", price: 300, img: "1596462906757", desc: "Traditional kajal eyeliner made from natural ingredients. Smudge-proof, long-lasting, and gentle on sensitive eyes.", sizes: ["3.5g","Pack of 2"], tags: ["beauty","kajal","eyeliner","natural","traditional"] },
  { cat: "BEAUTY", slug: "nail-polish-set", name: "Nail Polish — Nepal Colors", price: 500, img: "1571786183568", desc: "Set of 5 non-toxic nail polishes in Himalayan-inspired shades. Quick-dry, chip-resistant, and 7-free formula.", sizes: ["Set of 5"], tags: ["beauty","nail-polish","non-toxic","himalayan","colors"] },
  { cat: "BEAUTY", slug: "charcoal-face-wash", name: "Charcoal Face Wash — Nepal Detox", price: 450, img: "1556228578", desc: "Activated charcoal face wash for deep pore cleansing. Removes pollution particles and excess oil. Gentle daily formula.", sizes: ["100ml","200ml"], tags: ["beauty","face-wash","charcoal","detox","pollution"] },
  { cat: "BEAUTY", slug: "under-eye-cream", name: "Under Eye Cream — Himalayan Rest", price: 1200, img: "1598448794320", desc: "Targeted under-eye cream with caffeine and Himalayan botanicals. Reduces dark circles, puffiness, and fine lines.", sizes: ["15ml","30ml"], tags: ["beauty","eye-cream","caffeine","dark-circles","anti-aging"] },
  { cat: "BEAUTY", slug: "body-scrub-coffee", name: "Body Scrub — Nepal Coffee", price: 600, img: "1596462906757", desc: "Coffee and Himalayan salt body scrub. Exfoliates, smooths, and energizes skin. Made with organic Nepali coffee.", sizes: ["200g","400g"], tags: ["beauty","body-scrub","coffee","exfoliating","himalayan-salt"] },
  { cat: "BEAUTY", slug: "makeup-remover", name: "Makeup Remover — Kathmandu Clean", price: 500, img: "1571786183568", desc: "Gentle makeup remover with rose water and aloe vera. Dissolves even waterproof makeup without stripping skin.", sizes: ["100ml","200ml"], tags: ["beauty","makeup-remover","rose-water","aloe","gentle"] },
  { cat: "BEAUTY", slug: "hand-cream-himalayan", name: "Hand Cream — Nepal Soft", price: 350, img: "1556228578", desc: "Rich hand cream with Himalayan herbs and beeswax. Fast-absorbing, non-greasy, perfect for Kathmandu's dry winters.", sizes: ["50ml","100ml"], tags: ["beauty","hand-cream","beeswax","moisturizing","winter"] },
  { cat: "BEAUTY", slug: "dry-shampoo", name: "Dry Shampoo — Nepal Fresh", price: 550, img: "1598448794320", desc: "Waterless dry shampoo spray for quick refresh. Absorbs oil, adds volume. Perfect for trekking or power cut mornings.", sizes: ["150ml","250ml"], tags: ["beauty","dry-shampoo","waterless","trekking","refresh"] },
  { cat: "BEAUTY", slug: "body-oil-coconut", name: "Body Oil — Nepal Coconut", price: 700, img: "1596462906757", desc: "Cold-pressed coconut body oil with Himalayan essential oils. Multi-purpose for skin, hair, and massage.", sizes: ["100ml","200ml","500ml"], tags: ["beauty","body-oil","coconut","massage","multi-purpose"] },
  { cat: "BEAUTY", slug: "face-mist-rose", name: "Face Mist — Nepal Rose", price: 400, img: "1571786183568", desc: "Rose water face mist from the gardens of Pokhara. Hydrating, setting, and refreshing. Carry it everywhere in Kathmandu heat.", sizes: ["100ml","200ml"], tags: ["beauty","face-mist","rose-water","hydrating","pokhara"] },
  { cat: "BEAUTY", slug: "beauty-gift-set", name: "Beauty Gift Set — Nepal Glow Box", price: 3500, img: "1556228578", desc: "Curated beauty gift set with Nepal's finest — face serum, body lotion, lip balm, hand cream, and rose mist. Beautifully packaged.", sizes: ["Gift Set"], tags: ["beauty","gift-set","curated","glow","presentation"] },

  // Home (15)
  { cat: "HOME", slug: "bamboo-utensil-set", name: "Bamboo Utensil Set — Nepal Eco", price: 500, img: "1556228453", desc: "Eco-friendly bamboo utensil set — fork, spoon, knife, chopsticks, and straw. Travel case included. Say no to single-use plastic in Nepal.", sizes: ["One Size"], tags: ["home","bamboo","eco-friendly","utensil","zero-waste"] },
  { cat: "HOME", slug: "copper-water-bottle", name: "Copper Water Bottle — Nepal Ayurveda", price: 1200, img: "1586023492125", desc: "Hand-hammered copper water bottle following Ayurvedic tradition. Stores 1L, naturally purifies water, develops beautiful patina over time.", sizes: ["1L"], tags: ["home","copper","water-bottle","ayurveda","handmade"] },
  { cat: "HOME", slug: "dhaka-table-runner", name: "Dhaka Table Runner — Nepal Dining", price: 800, img: "1556228453", desc: "Elegant table runner in hand-woven Dhaka fabric. Vibrant geometric patterns that add Nepali warmth to any dining table.", sizes: ["40x150cm","40x180cm"], tags: ["home","dhaka","table-runner","dining","handwoven"] },
  { cat: "HOME", slug: "himalayan-salt-lamp", name: "Salt Lamp — Himalayan Glow", price: 1500, img: "1586023492125", desc: "Natural Himalayan salt lamp with wooden base. Warm ambient glow, air-purifying properties. Hand-mined from Khewra salt mines.", sizes: ["Small","Medium","Large"], tags: ["home","salt-lamp","himalayan","ambient","air-purifying"] },
  { cat: "HOME", slug: "wooden-serving-tray", name: "Serving Tray — Nepal Carved", price: 1800, img: "1556228453", desc: "Hand-carved wooden serving tray with traditional Nepali motifs. Mango wood with natural finish. Perfect for tea service or breakfast in bed.", sizes: ["30x20cm","40x30cm"], tags: ["home","serving-tray","wooden","carved","mango-wood"] },
  { cat: "HOME", slug: "felt-basket-set", name: "Felt Basket Set — Nepal Organize", price: 1200, img: "1586023492125", desc: "Set of 3 hand-felted wool baskets for storage and organization. Natural dyes in earth tones. Stackable when not in use.", sizes: ["Set of 3"], tags: ["home","felt","basket","storage","organization"] },
  { cat: "HOME", slug: "brass-diya-set", name: "Brass Diya Set — Nepal Light", price: 600, img: "1556228453", desc: "Set of 7 handcrafted brass diyas (oil lamps) for daily puja or Tihar festival. Traditional design with stable base.", sizes: ["Set of 7"], tags: ["home","diya","brass","puja","tihar"] },
  { cat: "HOME", slug: "ceramic-incense-holder", name: "Incense Holder — Nepal Ceramic", price: 400, img: "1586023492125", desc: "Handmade ceramic incense holder with ash-catching dish. Lotus and mandala designs. Fits stick and cone incense.", sizes: ["One Size"], tags: ["home","incense","ceramic","lotus","meditation"] },
  { cat: "HOME", slug: "handloom-towel-set", name: "Handloom Towel Set — Nepal Bath", price: 1500, img: "1556228453", desc: "Set of 4 handloom cotton towels in traditional Nepali patterns. Highly absorbent, quick-drying, and gets softer with each wash.", sizes: ["Set of 4"], tags: ["home","towel","handloom","cotton","bathroom"] },
  { cat: "HOME", slug: "wooden-wind-chime", name: "Wind Chime — Nepal Breeze", price: 800, img: "1586023492125", desc: "Handcrafted bamboo wind chime with wooden tubes. Gentle, soothing tones for garden or balcony. Natural finish.", sizes: ["One Size"], tags: ["home","wind-chime","bamboo","garden","soothing"] },
  { cat: "HOME", slug: "mandala-wall-clock", name: "Wall Clock — Nepal Mandala", price: 2000, img: "1556228453", desc: "Decorative wall clock with mandala design. Silent quartz movement, wooden frame. Combines function with Nepali art.", sizes: ["30cm","40cm"], tags: ["home","wall-clock","mandala","silent","decorative"] },
  { cat: "HOME", slug: "cotton-bedspread", name: "Bedspread — Nepal Comfort", price: 3500, img: "1586023492125", desc: "Hand-block printed cotton bedspread in traditional Nepali patterns. King or queen size. Reversible design, machine washable.", sizes: ["Queen","King"], tags: ["home","bedspread","cotton","hand-block","reversible"] },
  { cat: "HOME", slug: "herb-garden-kit", name: "Herb Garden Kit — Nepal Grow", price: 1200, img: "1556228453", desc: "Indoor herb garden kit with seeds, pots, and soil. Grow tulsi, cilantro, mint, and curry leaf at home. Perfect for Kathmandu apartments.", sizes: ["One Kit"], tags: ["home","herb-garden","indoor","growing","seeds"] },
  { cat: "HOME", slug: "carved-mirror-frame", name: "Mirror Frame — Nepal Carved", price: 4500, img: "1586023492125", desc: "Hand-carved wooden mirror frame with Newari floral patterns. Mango wood with natural oil finish. Statement piece for any room.", sizes: ["40x60cm","60x80cm"], tags: ["home","mirror","carved","newari","statement"] },
  { cat: "HOME", slug: "prayer-flag-garland", name: "Prayer Flag Garland — Nepal Blessing", price: 600, img: "1556228453", desc: "Decorative prayer flag garland for home, garden, or events. 50 cotton flags on natural jute string. Five sacred colors.", sizes: ["50 Flags","100 Flags"], tags: ["home","prayer-flag","garland","blessing","decoration"] },

  // Food (10)
  { cat: "FOOD", slug: "gundruk-dried", name: "Gundruk — Nepal's National Ferment", price: 400, img: "1563822796473", desc: "Traditional fermented leafy greens — Nepal's national side dish. Tangy, umami-rich, and packed with probiotics. Make gundruk ko achar or add to soups.", sizes: ["100g","250g","500g"], tags: ["food","gundruk","fermented","traditional","probiotic"] },
  { cat: "FOOD", slug: "chiura-beaten-rice", name: "Chiura — Beaten Rice Nepal", price: 300, img: "155667988", desc: "Traditional Nepali beaten rice (chiura/baji). Ready to eat — soak in water or milk. Essential for Dashain tika, festivals, and everyday breakfast.", sizes: ["500g","1kg","2kg"], tags: ["food","chiura","beaten-rice","dashain","breakfast"] },
  { cat: "FOOD", slug: "yomari-mix", name: "Yomari Mix — Newari Sweet", price: 600, img: "1563822796473", desc: "Pre-mixed Yomari flour for the iconic Newari festival dumpling. Just add water, fill with chaku (molasses) and coconut, steam. Makes 20 yomari.", sizes: ["500g","1kg"], tags: ["food","yomari","newari","sweet","festival"] },
  { cat: "FOOD", slug: "lapsi-candy", name: "Lapsi Candy — Nepal Sour Sweet", price: 250, img: "155667988", desc: "Traditional Nepali lapsi (hog plum) candy. Sweet, sour, and addictive. Made from wild lapsi fruits in the mid-hills of Nepal.", sizes: ["200g","500g"], tags: ["food","lapsi","candy","sour","traditional"] },
  { cat: "FOOD", slug: "black-tea-loose", name: "Black Tea — Nepal Orthodox Loose", price: 800, img: "1563822796473", desc: "Premium loose-leaf black tea from Ilam estates. Full-bodied, malty, with a hint of muscatel. Nepal's answer to Darjeeling.", sizes: ["100g","250g","500g"], tags: ["food","tea","black-tea","ilam","orthodox"] },
  { cat: "FOOD", slug: "sukuti-dried-meat", name: "Sukuti — Dried Buffalo Meat", price: 1200, img: "155667988", desc: "Traditional dried buffalo meat (sukuti) from the hills of Nepal. Smoky, chewy, and intensely flavorful. Fry with spices for the ultimate Nepali snack.", sizes: ["200g","500g"], tags: ["food","sukuti","dried-meat","buffalo","snack"] },
  { cat: "FOOD", slug: "masu-curry-mix", name: "Masu Curry Mix — Nepal Meat Spice", price: 500, img: "1563822796473", desc: "Pre-mixed spice blend for authentic Nepali meat curry (masu). Just add meat, water, and simmer. The taste of a Nepali kitchen.", sizes: ["100g","200g"], tags: ["food","curry-mix","masu","spice","cooking"] },
  { cat: "FOOD", slug: "churpi-hard-cheese", name: "Churpi — Himalayan Hard Cheese", price: 1500, img: "155667988", desc: "Traditional hard cheese made from yak or chauri milk in the Himalayan highlands. Chewy, smoky, and protein-rich. Long-lasting snack for trekkers.", sizes: ["100g","250g","500g"], tags: ["food","churpi","cheese","yak","himalayan"] },
  { cat: "FOOD", slug: "alu-tamatar-mix", name: "Aloo Tamatar Mix — Nepal Quick Curry", price: 350, img: "1563822796473", desc: "Instant aloo tamatar (potato-tomato) curry mix. Nepal's most beloved everyday curry — just add potatoes and water. Ready in 15 minutes.", sizes: ["200g","500g"], tags: ["food","curry-mix","aloo-tamatar","quick","everyday"] },
  { cat: "FOOD", slug: "juju-dhau-yogurt", name: "Juju Dhau — King Yogurt Mix", price: 500, img: "155667988", desc: "DIY kit for making Juju Dhau, the legendary 'King Yogurt' of Bhaktapur. Includes culture, instructions, and clay pot. Rich, creamy, and set like custard.", sizes: ["Kit for 1L"], tags: ["food","juju-dhau","yogurt","bhaktapur","traditional"] },
];

const marketplaceProducts = marketplaceDefs.map((m, i) => {
  const price = m.price + rand(-200, 500);
  return {
    id: `marketplace-${i}`,
    name: m.name,
    description: m.desc,
    price: Math.max(200, price),
    category: m.cat,
    image: img(m.img),
    sizes: m.sizes,
    colors: COLORS.neutral,
    isNew: i < Math.floor(marketplaceDefs.length * 0.2),
    rating: rating(),
    reviews: reviews(),
    stock: stock(),
    sold: sold(),
    freeShipping: freeShipping(price),
    shippingFrom: "Nepal",
    tags: m.tags,
  };
});

fs.writeFileSync(path.join(publicDir, "marketplace.json"), JSON.stringify(marketplaceProducts, null, 2));
console.log(`Wrote public/marketplace.json (${marketplaceProducts.length} products)`);

// ─── Summary ────────────────────────────────────────────────────────
console.log("\n=== CATALOG SUMMARY ===");
console.log(`products.json:    ${allProducts.length} products`);
console.log(`traditional.json: ${traditionalProducts.length} products`);
console.log(`marketplace.json: ${marketplaceProducts.length} products`);
console.log(`TOTAL:            ${allProducts.length + traditionalProducts.length + marketplaceProducts.length} products`);

const categoryCounts = {};
allProducts.forEach(p => { categoryCounts[p.category] = (categoryCounts[p.category] || 0) + 1; });
console.log("\nCategory breakdown (products.json):");
Object.entries(categoryCounts).forEach(([cat, count]) => {
  console.log(`  ${cat}: ${count}`);
});
